## Need help?


### Questions

If after repeated tries, checking the [help files](../reference/index.html), the [examples](../articles/Get_started.html) and [vignettes](../articles/vignettes_blogdown/quick-start-examples.html), you can't figure out why sequoia isn't working the way you think it should be working: please do feel free to email me at <jisca.huisman at gmail.com>. Usually I'll get back to you within 1--2 days (during European daytime). 

For example:

- It won't accept the input data
    - Are you really sure there aren't any weird symbols in the datafile?
- Assignment rate is (close to) zero, while you are sure there are relatives in the dataset
    - Are you really sure the genotyping error rate is as low as you claim it to be?
    - Are you really sure `sequoia()` is able to distinguish between different kind of relatives in your dataset? Please see [here](../articles/vignettes_blogdown/faq.html) in the main vignette
    - Are you really sure those genotypes belong to relatives? Did you try `CalcPairLL()` ?
- You are getting an error or warning message you can't make sense of, or which stats "Please report bug"
    - Please do email me; something may have slipped through the input check. You can check the [changelog](././news) for bugs that have been patched in the development version
    


### Consultancy work
If you do not have the time or manpower to perform pedigree reconstruction (and to get familiar with yet another piece of software / R package), I may be able to assist you. Please email me to discuss possibilities and fees. 

For example:

- Determine the minimum number of SNPs required to reconstruct a pedigree with 99% accuracy, exploring different plausible pedigrees / mating systems, sampling rates and genotyping errors
- Perform data quality control, and determine a subset of SNPs that will maximise completeness and accuracy of the reconstructed pedigree
- Run pedigree reconstruction using a variety of input parameters, and summarise the findings in a report
- Write R functions to extract data or summary statistics from the sequoia output in the format you require




## Want to help?

Everyone who reports a bug is contributing to improve `sequoia`, and these contributions are much appreciated!

If you have ideas or suggestions for new or improved functions, and/or wish to contribute to `sequoia`, or collaborate in some other way, please do contact me :-).  




<!---
### Donate
`sequoia` was initially developped while I was employed by the [Rum red deer project](http://rumdeer.biology.ed.ac.uk/) at the University of Edinburgh, but a
 substantial part was written in my own time. And although I thoroughly enjoy helping people to reconstruct pedigrees for an amazing range of species, user support can be quite time consuming. 

I very much wish `sequoia` to remain free to use for everyone, as some users are likely to have very limited budgets, e.g. those working in conservation. But if you do have the financial means, a donation via [] would be greatly appreciated. 
--->






